<h2><i class="fa fa-lock"></i> Se connecter avec un compte utilisateur</h2>
	<form action="<?= $requestUrl ?>/user/Login" method='post' class="generic-form" data-form>
<aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
        <p></p>
    </aside>
    <?php if(isset($errorMessage)): ?>
    <aside class="error-message">
        <p><?= $errorMessage; ?></p>
		</aside>
		<?php endif; ?>
<fieldset>
	<legend>Informations d'authentification</legend>
		<ul>
			<li>
				<label for="text">Email : </label>
				<input type="text" name="Login" id="Login" requierd  data-required data-name='Identifiant' value="<?= $Login ?>">
			</li>
			<li>
				<label for="Password">Password : </label>
				<input type="Password" name="Password" id="Password" requierd data-required data-name='Mots de passe'>
			</li>
	</ul>
</fieldset>
		<ul>
			<li>
				<input type="submit" name="submit" value="submit" class="button button-primary">
				<a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
			</li>
		</ul>
	</form>