<?php if($_SESSION['admin'] === 'on'): ?>
<?php //var_dump($_SESSION['admin']) ?>
	<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <?php //var_dump($_SESSION);
							//var_dump($listMeal); ?>
        <?php foreach($listMeal as $oneMeal): ?>
        <tr>
						<td><img src="<?= $wwwUrl ?>/images/meals/<?= $oneMeal['Photo']?>" alt=""></td>
						<td>
							<strong><a href="<?= $requestUrl; ?>/Meal?produit_id=<?= $oneMeal['Id']?>"><?= $oneMeal['Name']?></a></strong>
							<p><?= $oneMeal['Description']?></p>
						</td>
						<td class="number"><strong><?= number_format($oneMeal['SalePrice'],2);?></strong> €</td>
						<td>
							<form action="<?= $requestUrl; ?>/Admin/List/Modification" method="POST">
								<input type="hidden" name="meal_Id" value='<?= $oneMeal['Id']; ?>'>
								<input type="submit" value="Modifier" class="button button-primary small">
							</form>
						</td>
				</tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php endif; ?>