<!-- Message de notification -->

<!-- Code HTML à écrire -->

<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <?php //var_dump($listMeals); ?>
        <?php foreach($listMeals as $oneMeal): ?>
        <tr>
						<td><img src="<?= $wwwUrl ?>/images/meals/<?= $oneMeal['Photo']?>" alt=""></td>
						<td>
							<strong><a href="<?= $requestUrl; ?>/Meal?produit_id=<?= $oneMeal['Id']?>"><?= $oneMeal['Name']?></a></strong>
							<p><?= $oneMeal['Description']?></p>
						</td>
						<td class="number"><strong><?= number_format($oneMeal['SalePrice'],2);?></strong> €</td>
				</tr>
        <?php endforeach; ?>
    </tbody>
</table>