<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Chez Paolo</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/JqueryUi/jquery-ui.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/JqueryUi/jquery.ui.timepicker.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-cart.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
    <script src="<?= $wwwUrl ?>/js/classes/FormValidator.class.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            Restaurant - Chez Paolo !
        </a>
    </h1>
    <?php if($flashBag->hasMessages() === true): ?>
    <aside class='notice' id="notice">
			<p><strong><?= $flashBag->fetchMessage(); ?></strong></p>
    </aside>
    <?php endif; ?>
</header>
<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
       <li>
       	<a  class="button button-primary" href="<?= $requestUrl ?>">Accueil</a>
       </li>
       <?php if($userSession->isAuthenticated()): ?>
       <li>
       	<a  class="button button-primary" href="<?= $requestUrl ?>/Booking">Booking</a>
       </li>
       <li>
       	<a  class="button button-primary" href="<?= $requestUrl ?>/Order">Commander</a>
       </li>
       <li class="layout-right">
           <p class="welcome">Bonjour <strong><?= $userSession->getFullName(); ?></strong></p>
           <a class="button button-primary" href="<?= $requestUrl ?>/user/Logout?logout=out">Deconnexion</a>
       </li>
      <?php elseif (empty($_SESSION['admin']) == false): ?>
      	<li class="layout-right">
					<a class="button button-primary" href="<?= $requestUrl ?>/user/Logout?logout=out">Deconnexion</a>
				</li>
				<li>
					<a class="button button-primary" href="<?= $requestUrl ?>/Admin/List">List Produit</a>
				</li>
				<li>
					<a class="button button-primary" href="<?= $requestUrl ?>/Admin/List/Add">Ajouter Produit</a>
				</li>
       <?php else: ?>
        <li>
            <a class="button button-primary" href="<?= $requestUrl ?>/User">Créer un compte</a>
        </li>
        <li class="layout-right">
					<a class="button button-primary" href="<?= $requestUrl ?>/user/Login">Connexion</a>
				</li>
				<?php endif; ?>
    </ul>
</nav>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par Paolo</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/jquery-2.2.0.min.js"></script>
<script src="<?= $wwwUrl ?>/JqueryUi/jquery-ui.js"></script>
<script src="<?= $wwwUrl ?>/JqueryUi/jquery.ui.timepicker.js"></script>
<script src="<?= $wwwUrl ?>/js/checkAjax.js"></script>
<script src="<?= $wwwUrl ?>/js/main.js"></script>
</body>
</html>