<?php switch($Error): ?>
<?php case 1: ?>
	<h2 style="text-align : center">Le Proudit N'existe Pas</h2>
<?php break; ?>
<?php case 2: ?>
	<h2 style="text-align : center">On ne hack pas mon site !!!!!!!!!!!!!!!!</h2>
	<img src="http://iletaitungeek.com/wp-content/uploads/2015/08/dark-vador-aura-sa-ps4-collector-une.jpg" width="100%;">
<?php break; ?>
<?php case 3: ?>
	<h2 style="text-align : center">Are you An Hacking skywalker ??????????</h2>
	<img src="http://iletaitungeek.com/wp-content/uploads/2015/08/dark-vador-aura-sa-ps4-collector-une.jpg" width="100%;">
<?php break; ?>
<?php case 4 : ?>
	<h2 style="text-align : center">Votre email n'existe pas</h2>
<?php break; ?>
<?php case 5 : ?>
	<h2 style="text-align : center">Mots de Passe incorrecte</h2>
<?php break; ?>
<?php endswitch; ?>


<h2 style="text-align : center">Vous allez être redigeré vers la page d'accueil dans 10 seconde!!!!!!</h2>
<h2 style="text-align : center">Bisous</h2>