	<?php if(!isset($resultat)): ?>
		<?php if(isset($Error)): ?>
		<h2 style='text-align : center' class=".generic-form .error-message"><?= $Error; ?></h2>
		<?php endif; ?>


			<form action="<?= $requestUrl ?>/Booking" method="post" class="generic-form">
				<fieldset>
					<legend>Informations</legend>
					<ul>
					<li>
						<label for="dateResa" class="generic-form">Date Réservation</label>
						<input type="text" name="dateResa" id="dateResa" class="datepicker generic-form">  
					</li>
					<li>
						<label for="timeResa" class="generic-form"> Heure Réservation</label>
						<input type="text" name="timeResa" class="timeResa generic-form"> 
					</li>
					<li>
						<label for="NumberOfSeats" class="generic-form">Nombre de personne</label>
						<input type="number" name="NumberOfSeats" id="NumberOfSeats" class="generic-form"> 
					</li>
					<li id="parentSubmitBooking">
						<input type="submit" name="submit" value="envoyer" class="button button-primary" id="submitBooking"> 
					</li>
					<li id="errorAjax"></li>
					</ul>
				</fieldset>
		</form>	
<?php endif; ?>



<?php if(isset($bookingList)) : ?>
<section>
<?php foreach($bookingList as  $oneBooking) : ?>
<fieldset>
	<form action="<?= $requestUrl ?>/Booking/Supbooking" method="post" class="generic-form">
	<input type="hidden" name="bookingId" value="<?= $oneBooking['Id']; ?>">
	<input type="hidden" name="bookingDate" value="<?= $oneBooking['BookingDate']; ?>">
		<legend>Numero de réservation : <?= $oneBooking['Id']; ?></legend>
		<p>Date : <?= $oneBooking['BookingDate']; ?></p>
		<p>Heure : <?= $oneBooking['BookingTime']; ?></p>
		<p>Nombre de couvert : <?= $oneBooking['NumberOfSeats']; ?></p>
		<?php if($now < new DateTime($oneBooking['BookingDate'])): ?>
		<input type="submit" name="supprimer" value="supprimer" class="button button-primary">
		<?php endif; ?>
		<!-- REQUET SUPRESSION-->
</form>
</fieldset>
<?php endforeach; ?>
	
</section>

<?php endif; ?>
	