<aside id="card">
	
</aside>
   

   <table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <?php //var_dump($_SESSION);//var_dump($listMeals); ?>
        <?php foreach($listMeals as $oneMeal): ?>
        <tr>
						<td><img src="<?= $wwwUrl ?>/images/meals/<?= $oneMeal['Photo']?>" alt=""></td>
						<td>
							<strong><a href="<?= $requestUrl; ?>/Meal?produit_id=<?= $oneMeal['Id']?>"><?= $oneMeal['Name']?></a></strong>
						</td>
						<td class="number"><strong><?= number_format($oneMeal['SalePrice'],2);?></strong> €</td>
						<td class="addCard">
						<input type="number" data-id="<?= $oneMeal['Id']?>" class="quantity" data-name='<?= $oneMeal['Name']?>'>
						<input type="button" name="add" value="Ajouter au Panier" class="add button button-primary small">
						<p></p>
						</td>
				</tr>
        <?php endforeach; ?>
    </tbody>
</table>