<aside id="card">
</aside>


<!--   Autre solution-->
<form action="" method="POST" class="generic-form" id="orderForm" data-form>
	<aside class="error-message hidden">
		<h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
		<p></p>
	</aside>
	<fieldset>
        <legend>Ajouter un article</legend>
			<input type="hidden" name="salePrice" id="salePrice">
			<ul>
				<li>
					<label for="meal">Faites Vos choix</label>
					<select name="meal" id="meal">
						<?php foreach($listMeals as $oneMeal): ?>
						<option value="<?= $oneMeal['Id']?>"><?= $oneMeal['Name']?></option>
						<?php endforeach; ?>
					</select>
					<article class="meal-details no-left-label" id="meal-details">
						<img src="#" alt="">
						<p></p>
						<span>Prix : <strong></strong></span>
					</article>
				</li>
				<li class="no-left-label">
					<input type="text" name="quantity" id="quantity" class="quantity" maxlength=3 data-required data-name="quantite" data-type="positive-integer">
				</li>
				<li>
					<button class="no-left-label button
button-primary"><i class="fa fa-cart-arrow-down"></i> Ajouter au panier</button>
				</li>
			</ul>
	</fieldset>
</form>






<!--Ma solution-->


   <table class="generic-table meal-list addCard">
    <caption>Carte du restaurant</caption>
    <tbody>
		<form action="" method="POST" id="OrderFormOneByOne">
			<?php //var_dump($_SESSION);//var_dump($listMeals); ?>
			<?php foreach($listMeals as $oneMeal): ?>
			<tr>
				<td>
					<img src="<?= $wwwUrl ?>/images/meals/<?= $oneMeal['Photo']?>" alt="<?= $oneMeal['Name']?>">
				</td>
				<td>
					<strong>
						<a href="<?= $requestUrl; ?>/Meal?produit_id=<?= $oneMeal['Id']?>"><?= $oneMeal['Name']?></a>
					</strong>
				</td>
				<td class="number">
					<p><strong><?= number_format($oneMeal['SalePrice'],2);?></strong> €</p>
				</td>
				<td>
					<label for="quantity">Quantités souhaités</label>
					<input type="number" name="quantity" class="quantity" data-id="<?= $oneMeal['Id']?>"
						   data-name='<?=
					$oneMeal['Name']?>'>
				</td>
				<td>
					<input type="button" name="add" value="Ajouter au Panier" class="add button button-primary small">
					<p></p>
				</td>
			</tr>
			<?php endforeach; ?>
		</form>
    </tbody>
</table>


<script src="<?= $wwwUrl ?>/js/classes/OrderForm.class.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/OrderForm2.class.js"></script>