<h2><i class="fa fa-lock"></i> Se connecter comme Admin</h2>
	<form action="<?= $requestUrl ?>/Admin" method='post' class="geneNameric-form">
<aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
        <p></p>
    </aside>
<fieldset>
	<legend>Informations d'authentification</legend>
		<ul>
			<li>
				<label for="Name">Identifiant : </label>
				<input type="text" name="Name" id="Name" requierd  data-required class="generic-form" data-form>
			</li>
			<li>
				<label for="Password">Password : </label>
				<input type="Password" name="Password" id="Password" requierd data-required>
			</li>
	</ul>
</fieldset>
		<ul>
			<li>
				<input type="submit" name="submit" value="submit" class="button button-primary">
				<a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
			</li>
		</ul>
	</form>